---
abstract: 'Simple structured log messages'
author:
  - 'AND COPYRIGHT'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Message-Structured
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  JSON::Any: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Role::Parameterized: 0
  MooseX::Role::WithOverloading: 0
  MooseX::Storage: 0.26
  MooseX::Types: 0
  MooseX::Types::Common: 0
  MooseX::Types::ISO8601: 0.02
  Sys::Hostname: 0
  namespace::autoclean: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/log-message-structured.git
version: 0.004
